name: Check PR Build & Tests 

on:
  push:
    branches:
      - main
      - sandy/pr_build
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ hashFiles('requirements.txt') }}

      - name: Cache mypy
        uses: actions/cache@v4
        with:
          path: ./.mypy_cache
          key: ${{ hashFiles('pyproject.toml', 'requirements.txt') }}

      - name: Install uv
        run: python -m pip install uv

      - name: Install Dependencies
        run: |
          uv pip sync --system requirements.txt
          uv pip install --system -e .

      - name: Run Lint
        run: |
          make lint

      - name: Run format
        run: |
          make format
          git update-index --refresh && git diff-index --quiet HEAD -- || git diff --exit-code

      - name: Run Test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AZURE_OPENAI_API_BASE: ${{ secrets.AZURE_OPENAI_API_BASE }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: | 
          make unit_test